### ISSUE TITLE
Split SQL View creation from syncdb

### ISSUE THREAD

**Issue by scott-w** [zacharyvoase/django-postgres#2]
Creating SQL Views should have its own management command. This will make it easier for django-postgres to run alongside South.

You will no longer need to manage the views with South; instead you run (say) `python manage.py sync_pgviews` after migrating.

The biggest advantage of this would be to prevent developers from having to maintain multiple versions of a view as the database changes.

**Comment by scott-w** [comment]
Can sync all apps. Need to add ability to synchronise a single app by name.

**Comment by zacharyvoase** [comment]
I'm not sure I understand why we should have a separate management command, rather than just using the South `post_migrate` signal: http://south.readthedocs.org/en/latest/signals.html#post-migrate

**Comment by scott-w** [comment]
My thinking is that we should disassociate the creation of views from the migration process.

For example, we might have an app that has no migrations, because it's an app that only has SQL Views. We can't `syncdb` because the tables it depends on don't exist yet, and South won't see it, so `post_migrate` doesn't work either.

We shouldn't run `migrate` before `syncdb` because models "managed" by South may depend on "unmanaged" models.

Using an extra command, we can simplify our deployment process to:

``` bash
python manage.py syncdb
python manage.py migrate
python manage.py sync_pgviews
```

And no longer worry about any dependencies that Views may have.

**Comment by zacharyvoase** [comment]
Closing this issue, so we can keep the pull request as the canonical forum for discussing this.
