### ISSUE TITLE
CIText

### ISSUE THREAD

**Issue by dstufft** [zacharyvoase/django-postgres#6]
Any interest in support for [citext](http://www.postgresql.org/docs/9.2/static/citext.html)?

If so I'll write a PR and send it to you.

**Comment by zacharyvoase** [comment]
I’m at DjangoCon Europe and Christophe Pettus just mentioned it. Let’s do it. I’d assume you could inherit from `models.TextField`, right?

**Comment by dstufft** [comment]
Yup, it's a simple addition, `CaseInsensitiveTextField` and `CaseInsensitiveCharField` and just subclass from their respective fields and change the db type. I was going to do it inline in my project but I figured it made sense to have it here.
